routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('dashboard.index');
})->middleware('auth');*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/orders', 'OrdersController@index');

Route::get('/order/{id}', 'OrdersController@show');

Route::get('/order/{id}/upload', 'OrdersController@ShowUploadLink');
Route::post('/order/{id}/upload', 'OrdersController@UploadLink');

Route::get('/order/{id}/status', 'OrdersController@StatusUpdate');

Route::get('/order/{id}/phase', 'OrdersController@PhaseUpdate');

Route::get('/order/{id}/invalid', 'OrdersController@InvalidFileUpdate');

Route::get('/allorders', 'OrdersController@ShowAllOrders');

Route::get('/doctors', 'DoctorsController@index');

Route::get('/doctor/{id}', 'DoctorsController@show');

Route::get('/fixorderstatus', 'OrdersController@FixOrderStatus');

Route::post('/push','PushController@store');
Route::get('/push','PushController@push')->name('push');

Route::get('/doctorfix','DoctorsController@fix');

Route::get('/revenue', 'RevenueController@index');

Route::resource('users', 'UsersController');

Route::namespace('Doc')->group(function () {
    Route::prefix('doc')->group(function () {
        Route::get('/', 'HomeController@index');
        
        Route::get('login', 'LoginController@showLoginFormUsers');
        Route::post('login', 'LoginController@checklogin');
        Route::get('logout', 'LoginController@logout');
        Route::post('logout', 'LoginController@logout');
        
        Route::get('/order/{id}', 'OrdersController@show');
        Route::get('/orders', 'OrdersController@ShowOngoing');
        Route::get('/history', 'OrdersController@ShowHistory');
        Route::get('/order/{id}/approve', 'OrdersController@Approve');
        Route::get('/invoice/{id}', 'InvoiceController@ShowInvoice');
        
        Route::get('/new_order',function(){
            return view('doc.orders.new');
        });
        
        Route::resource('profile', 'ProfileController');
        
        Route::get('/account', 'AccountController@index');
        
        Route::get('/price', function(){
            return view('doc.price_structure');
        });
    });
});

app/ImageDoc.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Order;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;


class ImageDoc extends Authenticatable
{
    use Notifiable;
    
    // public $timestamps = false; 
    protected $table = 'imagedoc';
    
    protected $fillable = [
        'email', 'password',
    ];
    
    protected $hidden = [
        'password', 'remember_token',
    ];
    
    public function orders()
    {
        return $this->hasMany('App\Order', 'email', 'email');
    }
    
    public function getTotalOrdersAttribute()
    {
        return $this->orders->count();
    }
    
    public function getTotalAmountAttribute()
    {
        return Order::where('imagedoc_id',$this->id)
                        ->sum('total');
    }
}

app/Http/Controllers/DoctorsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\ImageDoc;
use App\Order;

class DoctorsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index() {
        $doctors = ImageDoc::orderBy('id','desc')
                            ->get();
                            
        /*-----Top Doctors---------*/
        $imagedoc_ids = Order::all()
                            ->groupBy('imagedoc_id')
                            ->toArray();
                            
        $imagedocs = [];
        
        foreach($imagedoc_ids as $key=>$value) {
            $doc_name = ImageDoc::whereId($key)
                                    ->first()->name;
            $imagedocs[$doc_name] = Order::where('imagedoc_id',$key)
                                        ->sum('total');
        }
        arsort($imagedocs);
        $topDocs = array_slice($imagedocs, 0, 5, true);
        
        /*-------Top Countries-------*/
        
        $countries = Order::select(['country'])
                            ->groupBy('country')
                            ->whereNotNull('country')
                            ->pluck('country')
                            ->toArray();
                            
        $country_values = [];                  
        foreach($countries as $country) {
            $country_values[$country] = Order::where('country', $country)
                                        ->sum('total');
        }
        arsort($country_values);
        $topCountries = array_slice($country_values, 0, 5, true);
        
        $data = ['doctors' => $doctors, 'topDocs' => $topDocs, 'topCountries' => $topCountries];
        return view('dashboard.doctors.index')->with($data);
    }
    
    public function show($id) {
        $doctor = ImageDoc::find($id);
        $data = ['doctor' => $doctor];
        return view('dashboard.doctors.show')->with($data);
    }
    
    public function fix() {
        $imagedoc = ImageDoc::all();
        foreach($imagedoc as $doc) {
            $order = Order::where('email',$doc->email)
                            ->update(['imagedoc_id' => $doc->id]);
        }
        
        return "Success";
    }
}

resources/views/dashboard/doctors/index.blade.php
@extends('layouts.master')

@section('page-title', 'Doctors')

@section('style')
  @parent
<!-- DataTables -->
  <link rel="stylesheet" href="/vendor/adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
  <style type="text/css">
    .products-list .product-info {
        margin-left: 0;
    }
  </style>
@endsection

@section('breadcrumb')
<ol class="breadcrumb float-sm-right">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item active">Doctors</li>
</ol>
@endsection

@section('content')
<!-- Main content -->
    <section class="content">
        <div class="container-fluid">
          <div class="row">
          <div class="col-md-4">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Top 5 Doctors</h3>

                <!--<div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse">
                    <i class="fas fa-minus"></i>
                  </button>
                  <button type="button" class="btn btn-tool" data-card-widget="remove">
                    <i class="fas fa-times"></i>
                  </button>
                </div>-->
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <ul class="products-list product-list-in-card pl-2 pr-2">
                  @foreach($topDocs as $key=>$docs)
                  <li class="item">
                    <div class="product-info">
                      <a href="javascript:void(0)" class="product-title text-capitalize">{{$key}}
                        <span class="badge badge-success float-right">${{$docs}}</span></a>
                    </div>
                  </li>
                  @endforeach
                  <!-- /.item -->
                </ul>
              </div>
              <!-- /.card-body -->
            </div>
        </div>
        
        <div class="col-md-4">
          <div class="card">
              <div class="card-header">
                <h3 class="card-title">Top 5 Countries</h3>

                <!--<div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse">
                    <i class="fas fa-minus"></i>
                  </button>
                  <button type="button" class="btn btn-tool" data-card-widget="remove">
                    <i class="fas fa-times"></i>
                  </button>
                </div>-->
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <ul class="products-list product-list-in-card pl-2 pr-2">
                  @foreach($topCountries as $key=>$value)
                  <li class="item">
                    <div class="product-info">
                      <a href="javascript:void(0)" class="product-title text-capitalize">{{$key}}
                        <span class="badge badge-success float-right">${{$value}}</span></a>
                    </div>
                  </li>
                  @endforeach
                  <!-- /.item -->
                </ul>
              </div>
              <!-- /.card-body -->
            </div>
          </div>
          </div>
          
<div class="card">
            <!-- /.card-header -->
            <div class="card-body">
                <div class="table-responsive">
              <table id="doctorsTable" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Name</th>
                  <th>Contact</th>
                  <th>Email</th>
                  <th>Country</th>
                  <th>Total Orders</th>
                  <th>Amount</th>
                  <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($doctors as $doctor)
                <tr>
                  <td>{{$doctor->name}}</td>
                  <td>{{$doctor->mobile}}</td>
                  <td>{{$doctor->email}}</td>
                  <td>-</td>
                  <td>{{$doctor->total_orders}}</td>
                  <td>{{$doctor->total_amount}}</td>
                  <td>
                    <a href="/doctor/{{$doctor->id}}" class="btn btn-info btn-sm">Details</a>
                  </td>
                </tr>
                @endforeach
                </tfoot>
              </table>
              </div>
            </div>
            <!-- /.card-body -->
          </div>
        </div>
    </section>
@endsection

@section('script')
  @parent
<script src="/vendor/adminlte/plugins/datatables/jquery.dataTables.js"></script>
<script src="/vendor/adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
<script>
$("#doctorsTable").DataTable({
    	"aaSorting": [],
        "columnDefs": [
            {
            "targets": 6,
            "orderable": false
            },
            {
            "targets": 5,
		        render: function ( data, type, row, meta ) {
		        	return '$' + data;
		        }
            }
            ]
    });
</script>
@endsection

resources/views/dashboard/doctors/show.blade.php
@extends('layouts.master')

@section('page-title', 'Doctor Details')

@section('style')
  @parent
<!-- DataTables -->
  <link rel="stylesheet" href="/vendor/adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
@endsection

@section('breadcrumb')
<ol class="breadcrumb float-sm-right">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item"><a href="/doctors">Doctors</a></li>
    <li class="breadcrumb-item active">Doctor Details</li>
</ol>
@endsection

@section('content')
<!-- Main content -->
    <section class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-lg-4">
            <div class="card">
            <!-- /.card-header -->
            <div class="card-body">
              <div class="row">
              <div class="col-md-4">
                <img class="img img-fluid rounded-circle" src="/vendor/adminlte/img/avatar.png"></img>
              </div>
              <div class="col-md-8">
                <strong>Name:</strong>{{$doctor->name}}<br/>
                <strong>Email:</strong>{{$doctor->name}}<br/>
                <strong>Contact:</strong>{{$doctor->mobile}}<br/>
                <strong>Address:</strong>{{$doctor->address}}<br/>
              </div>
              </div>
            </div>
            </div>
            </div>
            <div class="col-lg-4">
              <div class="small-box bg-info">
                <div class="inner">
                  <p>Total Orders</p>
                  <h3>{{$doctor->total_orders}}</h3>
                </div>
              </div>
            </div>
            <div class="col-lg-4">
              <div class="small-box bg-success">
                <div class="inner">
                  <p>Total Purchase Amount</p>
                  <h3>$ {{$doctor->total_amount}}</h3>
                </div>
              </div>
            </div>
          </div>
          
        <div class="card">
            <div class="card-header">
              <h3 class="card-title">ORDER HISTORY</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <div class="table-responsive">
              <table id="ordersTable" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Id</th>
                  <th>Service</th>
                  <th>Date</th>
                  <th>Price</th>
                  <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($doctor->orders as $order)
                <tr>
                  <td>{{$order->id}}</td>
                  <td>{{showServicesFromArray($order->services)}}</td>
                  <td>{{$order->created_at->format('d/m/Y')}}</td>
                  <td>{{$order->total}}</td>
                  <td>
                    <a href="/order/{{$order->id}}" class="btn btn-info btn-sm">Details</a>
                  </td>
                </tr>
                @endforeach
                </tfoot>
              </table>
              </div>
            </div>
            <!-- /.card-body -->
          </div>  
          
        </div>
    </section>
@endsection

@section('script')
  @parent
<script src="/vendor/adminlte/plugins/datatables/jquery.dataTables.js"></script>
<script src="/vendor/adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
<script>
$("#ordersTable").DataTable({
    	"aaSorting": [],
        "columnDefs": [
            {
            "targets": 4,
            "orderable": false
            },
            {
            "targets": 3,
		        render: function ( data, type, row, meta ) {
		        	return '$' + data;
		        }
            }
            ]
    });
</script>
@endsection